package com.example.financeanalyzer.feature_finance.domain.use_case.transactions

import com.example.financeanalyzer.feature_finance.domain.use_case.GetAllTransactionsGroupedByCategoryFromCurrentMonth
import com.example.financeanalyzer.feature_finance.domain.use_case.GetConstantTransactions
import com.example.financeanalyzer.feature_finance.domain.use_case.GetFirstDayOfTheMonthInMillis

data class TransactionsUseCases(
    val getAllTransactionsGroupedByCategoryFromCurrentMonth: GetAllTransactionsGroupedByCategoryFromCurrentMonth,
    val getConstantTransactions: GetConstantTransactions,
    val getFirstDayOfTheMonthInMillis: GetFirstDayOfTheMonthInMillis
)
